### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by alasijia** [Zhongdao/Towards-Realtime-MOT#1]
您好！当我想运行demo的时候，发现没有权重文件。这个权重文件是train生成的吗？现在我可以通过运行train生成权重文件，然后运行demo吗？

**Comment by Zhongdao** [comment]
Sorry about that, I have not upload  the model weights yet. Please be patient and keep an eye on this project...  I will upload them as soon as possible. Thank you for your attention!

**Comment by alasijia** [comment]
非常感谢！
