### ISSUE TITLE
No module named 'maskrcnn_benchmark

### ISSUE THREAD

**Issue by onoderay** [Zhongdao/Towards-Realtime-MOT#10]
I'm sorry, this would be very naive question but I couldnt run demo because utils.py couldnt properly import maskrcnn_benchmark.layers.nms as nms

$ python demo.py --input-video path/to/your/input/video --weights path/to/model/weights
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/home/hoge/work/fisheye/Towards-Realtime-MOT/tracker/multitracker.py", line 10, in <module>
    from utils.utils import *
  File "/home/hoge/work/fisheye/Towards-Realtime-MOT/utils/utils.py", line 14, in <module>
    import maskrcnn_benchmark.layers.nms as nms
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

I tried to install by following this install.md instruction
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md
and I manage to install properly.
But how should I edit importing sentense like import maskrcnn_benchmark.layers.nms as nms?

my current working tree structure is like this.
dir(fisheye)/
├──Towards-Realtime-MOT (git cloned dir)
├── maskrcnn-benchmark (git cloned dir)

in the case I tried to edit utils.py path for maskrcnn by myself with begginer python knowledge like below.
from ..maskrcnn-benchmark import maskrcnn_benchmark.layers.nms as nms

However I failed to import with this error massage
from ..maskrcnn-benchmark import maskrcnn_benchmark.layers.nms as nms
SyntaxError: invalid syntax

Can someone help me please?

**Comment by DongDem** [comment]
You need build the maskrcnn_benchmark folder.
Follow this link https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md

**Comment by Zhongdao** [comment]
If you build maskrcnn_benchmark properly, a link will be automatically generated in your python site-package, so there is no need to care about where you put the source code.
Make sure you run this command when you build maskrcnn-benchmark:
`python setup.py build develop`

**Comment by feidasheng** [comment]
hello ,i follow  this link https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md  on my ubuntu 16.04,but display  the error  'cannot find /usr/local/cuda-10.0/bin/nvcc',i total follow this link ,why? thank you very  much

**Comment by Zhongdao** [comment]
@feidasheng The installation script cannot find nvcc, please make sure your CUDA is installed properly.

**Comment by feidasheng** [comment]
when i  build apex, it shows this error ,but i think my cuda is right.i  dont know what is wrong?
torch.__version__  =  1.0.0.dev20190328
setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
  warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
from :/usr/local/cuda-10.0/bin

running install
running bdist_egg
running egg_info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
reading manifest file 'apex.egg-info/SOURCES.txt'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'amp_C' extension
gcc -pthread -B /home/feidasheng/.conda/envs/maskrcnn_benchmark/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/TH -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/include/python3.7m -c csrc/amp_C_frontend.cpp -o build/temp.linux-x86_64-3.7/csrc/amp_C_frontend.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-10.0/bin/nvcc -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/TH -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/home/feidasheng/.conda/envs/maskrcnn_benchmark/include/python3.7m -c csrc/multi_tensor_sgd_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/multi_tensor_sgd_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -lineinfo -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-10.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1

**Comment by xiaocc612** [comment]
> If you build maskrcnn_benchmark properly, a link will be automatically generated in your python site-package, so there is no need to care about where you put the source code.
> Make sure you run this command when you build maskrcnn-benchmark:
> `python setup.py build develop`
I can't find setup.py in maskrcnn-benchmark file, what should I do to solve this?thank you!

**Comment by ThanhPham1987** [comment]
You have to check the version of pytorch for paper >=1.0.1 for paper. But pytorch for syncbn.py is 1.0. And pytorch for maskrcnn-benchmark is 1.0. We have many pytorch version. I had many issue from pytorch version.

**Comment by vusraju** [comment]
@Zhongdao , Thanks a lot for sharing your work. I am also having Pytorch and CUDA version issues while installing maskrcnn-benchmark. Could please mention the environment configuration that you used for training and testing the models? (I mostly need CUDA Version, CUDNN Version and Pytorch Version)

I will recreate your environment and try to do inference
TIA

**Comment by ThanhPham1987** [comment]
You have to use IDE pycharm to set up environment. You can communication to me via skype: quangthanh1987@gmail.com

**Comment by vusraju** [comment]
> You have to use IDE pycharm to set up environment. You can communication to me via skype: [quangthanh1987@gmail.com](mailto:quangthanh1987@gmail.com)

Hi, I am trying to set up environment on a linux server. I cannot use IDE. If I know the environment setting, I can make necessary installations.

**Comment by Chqbelief** [comment]
gcc -pthread -B /home/amax/anaconda3/envs/cq_tf10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/amax/anaconda3/envs/cq_tf10/lib/python3.6/site-packages/numpy/core/include -I../common -I/home/amax/anaconda3/envs/cq_tf10/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
gcc -pthread -shared -B /home/amax/anaconda3/envs/cq_tf10/compiler_compat -L/home/amax/anaconda3/envs/cq_tf10/lib -Wl,-rpath=/home/amax/anaconda3/envs/cq_tf10/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/../common/maskApi.o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -o build/lib.linux-x86_64-3.6/pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so
/home/amax/anaconda3/envs/cq_tf10/compiler_compat/ld: cannot find -lpthread
/home/amax/anaconda3/envs/cq_tf10/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by Zhongdao** [comment]
Hi guys,
When you compile pytorch and maskrcnn-benchmark, you may use different versions of the compiler, e.g. gcc/nvcc, and weird errors may occur.

This problem is now addressed. I have updated the repo and the codebase does not rely on maskrcnn-benchmark (spcifically its NMS module) anymore, but you need a newer version of pytorch (>1.2.0). Torchvision now has an official implementation of GPU NMS, which is very user-friendly.
