### ISSUE TITLE
IndexError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by hp-93** [Zhongdao/Towards-Realtime-MOT#105]
I trained with origin ccmcpe.json, theire is Error tips in test stage
Extracting pedestrain features...
Extracting 0/1750, # of instances 16, time 0.38 sec.
Extracting 40/1750, # of instances 740, time 0.15 sec.
Extracting 80/1750, # of instances 1562, time 0.16 sec.
Extracting 120/1750, # of instances 2167, time 0.15 sec.
Extracting 160/1750, # of instances 2625, time 0.16 sec.
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    opt=opt,
  File "train.py", line 159, in train
    test.test_emb(cfg, data_cfg, weights=latest, batch_size=batch_size, print_in                                                                                                                terval=40)
  File "/home/Towards-Realtime-MOT/test.py", line 191, in test_emb
    feat, label = out[:-1], out[-1].long()
IndexError: dimension specified as 0 but tensor has no dimensions

**Comment by hp-93** [comment]
output = model(imgs.cuda(), targets.cuda(), targets_len.cuda()).squeeze()( test.py  189行)
why the output shape of some images  is different？ 
right output:
![image](https://user-images.githubusercontent.com/35527573/75508258-76fc8200-5a1e-11ea-82f1-303056e70016.png)
wrong output:
![image](https://user-images.githubusercontent.com/35527573/75508273-8380da80-5a1e-11ea-8fe2-a1336df91fec.png)

**Comment by hp-93** [comment]
replace output = model(imgs.cuda(), targets.cuda(), targets_len.cuda()).squeeze() with  output = model(imgs.cuda(), targets.cuda(), targets_len.cuda()), just remove squeeze()

**Comment by jwnirvana** [comment]
I meet the same problem, and do the same change as you, but there is a new problem when testing:

================================================================================
dataset summary
OrderedDict([('caltech', 1311.0), ('citypersons', 0)])
total # identities: 1312
start index
OrderedDict([('caltech', 0), ('citypersons', 1311.0)])
================================================================================
      Image      Total          P          R        mAP
          6      30353          0          0          0      0.382s
        246      30353          0          0          0      0.165s
        486      30353          0          0          0      0.149s
        726      30353          0          0          0      0.154s
        966      30353          0          0          0      0.148s
       1206      30353          0          0          0      0.158s
       1446      30353          0          0          0      0.153s
       1686      30353          0          0          0      0.154s
       1926      30353          0          0          0      0.155s
       2166      30353          0          0          0      0.152s
       2406      30353          0          0          0      0.199s
       2646      30353          0          0          0      0.175s
       2886      30353          0          0          0      0.156s
       3126      30353          0          0          0      0.184s
       3366      30353          0          0          0      0.162s
       3606      30353          0          0          0      0.153s
       3846      30353          0          0          0      0.154s
       4086      30353          0          0          0      0.151s
       4326      30353          0          0          0      0.152s

       。。。。。。
      26166      30353          0          0          0      0.155s
      26406      30353          0          0          0      0.152s
      26646      30353          0          0          0      0.151s
      26886      30353          0          0          0      0.157s
      27126      30353          0          0          0      0.157s
      27366      30353          0          0          0      0.151s
      27606      30353          0          0          0      0.152s
      27846      30353          0          0          0      0.152s
      28086      30353          0          0          0      0.153s
      28326      30353          0          0          0      0.152s
      28566      30353          0          0          0      0.151s
      28806      30353          0          0          0      0.155s
      29046      30353          0          0          0      0.151s
      29286      30353          0          0          0      0.149s
      29526      30353          0          0          0       0.15s
      29766      30353          0          0          0      0.151s
      30006      30353          0          0          0      0.204s
      30246      30353          0          0          0      0.227s
      Image      Total          P          R        mAP
AP: 0.0000


================================================================================
dataset summary
OrderedDict([('caltech', 393.0), ('cuhksysu', 11934.0), ('prw', 934.0)])
total # identities: 13262
start index
OrderedDict([('caltech', 0), ('cuhksysu', 393.0), ('prw', 12327.0)])
================================================================================
Extracting pedestrain features...
Extracting 0/2334, # of instances 12, time 0.31 sec.
Extracting 40/2334, # of instances 546, time 0.20 sec.
Extracting 80/2334, # of instances 1130, time 0.18 sec.
Extracting 120/2334, # of instances 1705, time 0.18 sec.
Extracting 160/2334, # of instances 2163, time 0.18 sec.
Extracting 200/2334, # of instances 2510, time 0.21 sec.
Extracting 240/2334, # of instances 2842, time 0.17 sec.
Extracting 280/2334, # of instances 3204, time 0.17 sec.
Extracting 320/2334, # of instances 3510, time 0.18 sec.
Extracting 360/2334, # of instances 3967, time 0.17 sec.

。。。。。。
Extracting 2000/2334, # of instances 26360, time 0.22 sec.
Extracting 2040/2334, # of instances 27008, time 0.21 sec.
Extracting 2080/2334, # of instances 27680, time 0.20 sec.
Extracting 2120/2334, # of instances 28546, time 0.24 sec.
Extracting 2160/2334, # of instances 29673, time 0.20 sec.
Extracting 2200/2334, # of instances 30413, time 0.22 sec.
Extracting 2240/2334, # of instances 31371, time 0.24 sec.
Extracting 2280/2334, # of instances 32142, time 0.23 sec.
Extracting 2320/2334, # of instances 33047, time 0.19 sec.
Computing pairwise similairity...
33305 33305
Killed
