### ISSUE TITLE
ModuleNotFoundError: No module named 'lap'

### ISSUE THREAD

**Issue by huangpan2507** [Zhongdao/Towards-Realtime-MOT#107]
>>(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$ python demo.py --input-video  test/MOT16-12.mp4  --weights weights/jde_864x480_uncertainty.pt  --output-format video --output-root results/
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    from tracker.multitracker import JDETracker
  File "/home/huangpan/git_download/Towards-Realtime-MOT/tracker/multitracker.py", line 15, in <module>
    from tracker import matching
  File "/home/huangpan/git_download/Towards-Realtime-MOT/tracker/matching.py", line 7, in <module>
    import lap
ModuleNotFoundError: No module named 'lap'

my conda info show as below:

>>(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$ conda info

     active environment : Towards-Realtime-MOT
    active env location : /home/huangpan/anaconda3/envs/Towards-Realtime-MOT
            shell level : 2
       user config file : /home/huangpan/.condarc
>> populated config files : /home/huangpan/.condarc
          conda version : 4.8.1
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.30
  >>     base environment : /home/huangpan/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/huangpan/anaconda3/pkgs
                          /home/huangpan/.conda/pkgs
       envs directories : /home/huangpan/anaconda3/envs
                          /home/huangpan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.0 Linux/5.4.8-arch1-1 arch/ glibc/2.30
                UID:GID : 1001:1002
             netrc file : None
           offline mode : False

when I use pip install lap , it still have the same problem!  How can I fixed  it? 
any idea is appreciated!

**Comment by huangpan2507** [comment]
[I have  solve this problem.
](https://github.com/Zhongdao/Towards-Realtime-MOT/issues/38#issuecomment-553779985)

**Comment by Ursanon** [comment]
> [I have solve this problem.
> 
> just do like this:
> change models.py like this:
> batch_norm=nn.BatchNorm2d
> #SyncBN #nn.BatchNorm2d
> 
> ]([#38 (comment)](https://github.com/Zhongdao/Towards-Realtime-MOT/issues/38#issuecomment-553779985))

No need for this.

`pip install lap` solves everything
