### ISSUE TITLE
darknet74.conv trained on what object?

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#109]
On what objects(i.e pedestrian only, or general objects) is the darknet model trained on? If I want to train the whole system on some other object, say birds, can I train it on its dataset without changing darknet weights?

**Comment by WongKinYiu** [comment]
https://github.com/Zhongdao/Towards-Realtime-MOT#pretrained-model-and-baseline-models
It is ImageNet pre-trained model.

**Comment by PartheshSoni** [comment]
> https://github.com/Zhongdao/Towards-Realtime-MOT#pretrained-model-and-baseline-models
> It is ImageNet pre-trained model.

So we don't need to train darknet for objects other than pedestrians?

**Comment by WongKinYiu** [comment]
This repository joint train detector and embedder simultaneously. 
![image](https://user-images.githubusercontent.com/12152972/75864643-4f9e1e80-5e3d-11ea-90e2-2af3b26a70c4.png)

**Comment by Zhongdao** [comment]
@PartheshSoni  If you want to detect/track other objects than pedestrians, you also need to train with that class of objects as training data. The initial darknet weights are trained on ImageNet dataset for the classification task, it cannot be directly adapted for the detection task.
