### ISSUE TITLE
Will this code run with CUDA-10.2 ?

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#111]
I have just upgraded CUDA from 9.1 to 10.2, and the following error is encountered:

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=30 : unknown error
2020-03-04 14:11:47 [INFO]: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:50

**Comment by ajithvallabai** [comment]
@PartheshSoni  in which cuda version you were able to run ?
