### ISSUE TITLE
why use two different steps 1. association  with embedding and 2. association with IOU

### ISSUE THREAD

**Issue by ks322181** [Zhongdao/Towards-Realtime-MOT#114]
![multitracker](https://user-images.githubusercontent.com/58224797/76423925-817b2c00-63cd-11ea-8e22-bac4eea2e8fe.png)

Can i know what exactly these two steps in screenshots will do. i had confusion with these two steps.

Thanks in Advance

**Comment by Zhongdao** [comment]
This is a trick adapted from DeepSORT to improve tracking accuracy --- for those observations that fail to be associated by the appearance+motion score, we associate them to tracklets by a high motion similarity (IOU here).

**Comment by ks322181** [comment]
Thanks.
