### ISSUE TITLE
have bug in models.py

### ISSUE THREAD

**Issue by chaipangpang** [Zhongdao/Towards-Realtime-MOT#116]
I think there have bug in [models.py](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py)  Darknet init
```python
class Darknet(nn.Module):
    """YOLOv3 object detection model"""

    def __init__(self, cfg_dict, nID=0, test_emb=False):
```
```python
self.model = Darknet(opt.cfg, opt.img_size, nID=30)
```
where is `img_size` pramer?

**Comment by chaipangpang** [comment]
in lastest commit

**Comment by imchwan** [comment]
It looks like we need to call Darknet() without img_size, since Darknet class is reading img_size from cfg_dict.
> self.img_size = [int(self.module_defs[0]['width']), int(self.module_defs[0]['height'])]

So, I think we need to use it as:
`self.model = Darknet(opt.cfg, nID=30)`

**Comment by denverdash** [comment]
Yep I can also confirm that this is a bug.
