### ISSUE TITLE
That "pip install cython_bbox" in windows10 always meets errors

### ISSUE THREAD

**Issue by asian3** [Zhongdao/Towards-Realtime-MOT#117]
This is part of the error msg: 
ERROR: Failed building wheel for cython-bbox
  Running setup.py clean for cython-bbox
Failed to build cython-bbox
Installing collected packages: cython-bbox
    Running setup.py install for cython-bbox ... error
    ERROR: Command errored out with exit status 1:

**Comment by InzamamAnwar** [comment]
@asian3 please follow these steps
https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows

Worked perfectly in my case

**Comment by asian3** [comment]
> @asian3请按照以下步骤https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows
> 在我的案例中工作得非常完美

well done with your method,3Q
