### ISSUE TITLE
What is the format of dataset for evaluating the tracker, using track.py?

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#119]
I saw you mentioned MOT16 training data as default for evaluating, but what is the format of its labels? Is it like the ones used for training the tracker or like the default ones given by the challenge?

**Comment by Zhongdao** [comment]
The labels should be the MOT challenge format

**Comment by PartheshSoni** [comment]
Okay, thanks!
