### ISSUE TITLE
Need some help running Demo examples

### ISSUE THREAD

**Issue by imchwan** [Zhongdao/Towards-Realtime-MOT#120]
Dear @Zhongdao ,
First of all, thank you for sharing this great work!

I'm just trying to run the demo examples from the script below with your pretrained weights.
https://github.com/Zhongdao/Towards-Realtime-MOT#docker-demo-example

My running code:
_python demo.py --input-video /mnt/choong/Database/infiniq2018_PeopleCounting/videos_selected/PC_088_CAM3_2/videos/PC_088_CAM3_2_60sec.mp4 --weights /mnt/choong/Towards-Realtime-MOT/weights/jde.1088x608.uncertainty.pt --output-format video --output-root /mnt/choong/Towards-Realtime-MOT/output_

And I have below error messages...
It looks like something is wrong with Numba..but I'm not quite sure what's the problem.
Can you please point me out some clue?
Thank you in advance.

----ERROR MESSAGE-----
Namespace(cfg='cfg/yolov3_1088x608.cfg', conf_thres=0.5, input_video='/mnt/choong/Database/infiniq2018_PeopleCounting/videos_selected/PC_088_CAM3_2/videos/PC_088_CAM3_2_60sec.mp4', io
u_thres=0.5, min_box_area=200, nms_thres=0.4, output_format='video', output_root='/mnt/choong/Towards-Realtime-MOT/output', track_buffer=30, weights='/mnt/choong/Towards-Realtime-MOT/
weights/jde.1088x608.uncertainty.pt')

2020-03-19 11:42:05 [INFO]: Starting tracking...
Lenth of the video: 1799 frames
Start eval_seq
2020-03-19 11:42:11 [INFO]: Processing frame 0 (100000.00 fps)
/mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py:140: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "tlbr_to_tlwh" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py (143)

File "tracker/multitracker.py", line 143:
    def tlbr_to_tlwh(tlbr):
        ret = np.asarray(tlbr).copy()
        ^

  @staticmethod
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "tlbr_to_tlwh" was compiled in object mode without forceobj=True.

File "tracker/multitracker.py", line 142:
    @jit
    def tlbr_to_tlwh(tlbr):
    ^

  state.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "tracker/multitracker.py", line 142:
    @jit
    def tlbr_to_tlwh(tlbr):
    ^

  state.func_ir.loc))
/mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py:116: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "tlbr" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py (122)

File "tracker/multitracker.py", line 122:
    def tlbr(self):
        <source elided>
        """
        ret = self.tlwh.copy()
        ^

  @property
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "tlbr" was compiled in object mode without forceobj=True.

File "tracker/multitracker.py", line 118:
    @jit
    def tlbr(self):
    ^

  state.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "tracker/multitracker.py", line 118:
    @jit
    def tlbr(self):
    ^

  state.func_ir.loc))
/mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py:103: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "tlwh" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py (109)

File "tracker/multitracker.py", line 109:
    def tlwh(self):
        <source elided>
        """
        if self.mean is None:
        ^

  @property
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "tlwh" was compiled in object mode without forceobj=True.

File "tracker/multitracker.py", line 105:
    @jit
    def tlwh(self):
    ^

  state.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "tracker/multitracker.py", line 105:
    @jit
    def tlwh(self):
    ^

  state.func_ir.loc))
2020-03-19 11:42:12 [INFO]: name 'logger' is not defined

**Comment by Zhongdao** [comment]
2020-03-19 11:42:12 [INFO]: name 'logger' is not defined
It seems the logger is not properly initialized?

**Comment by imchwan** [comment]
Thank you for the comments.
I just added 
> from utils.log import logger
at multitracker.py, and that error was not seen.

And also I commented out jit at multitracker.py related to the Numba(using @jit...).

Still modifying codes a little to remove errors in the code, 
however, I think I'm doing something wrong...
But the problem is...I'm not sure what's the problem.
(It seems like it's only me that cannot run the demo ;( )

Can I check one more thing?
Below script is the only thing I need to do before running _python demo.py_, right?
```
docker build -t towards-realtime-mot docker/
docker run --rm --gpus all -v $(pwd)/:/Towards-Realtime-MOT -ti towards-realtime-mot /bin/bash
```
Thank you in advace!

**Comment by woailuoshenqi** [comment]
I have this problem, too. Have you solved?

**Comment by imchwan** [comment]
@woailuoshenqi 
I have pulled latest version which was updated by denverdash:bugfix (Bugfix #122).
Then the problem was solved. =)

**Comment by woailuoshenqi** [comment]
Thanks!

> @woailuoshenqi
> I have pulled latest version which was updated by denverdash:bugfix (Bugfix #122).
> Then the problem was solved. =)
Thanks！
