### ISSUE TITLE
Could find no file with path!!

### ISSUE THREAD

**Issue by tamamjerbi** [Zhongdao/Towards-Realtime-MOT#124]
Hello there,
I'm trying to run the demo but i have this issue, (i'm using windows 10), I'm still new to all this tracking so if anyone could help with detail would be much appreciated, 
thanks.
![error_msg](https://user-images.githubusercontent.com/20155571/77254580-8d3ade00-6c6a-11ea-84a3-d709227e8f30.jpg)

(realTimeMOT) C:\Users\Tamam Jerbi\PycharmProjects\Graduation_proj\Towards_real_time_MOT\Towards-Realtime-MOT>python demo.py --input-video ppl2.mp4 --weights weights\jde.1088x608.uncertainty.pt
Namespace(cfg='cfg/yolov3_1088x608.cfg', conf_thres=0.5, input_video='ppl2.mp4', iou_thres=0.5, min_box_area=200, nms_thres=0.4, output_format='video', output_root='results', track_buffer=30, weights='weights\\jde.1088x608.uncertainty.pt')

2020-03-22 18:16:41 [INFO]: Starting tracking...
Lenth of the video: 2054 frames
2020-03-22 18:16:41 [INFO]: __init__() got multiple values for argument 'nID'

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 000001b5d11d19c0] Could find no file with path 'results\frame/%05d.jpg' and index in the range 0-4
results\frame/%05d.jpg: No such file or directory

**Comment by Zhongdao** [comment]
Hi, @tamamjerbi 
This is caused by a previous bug, which is fixed in the latest version, please make sure you are using the latest version of the code

**Comment by tamamjerbi** [comment]
thanks a lot for your fast response, and thank you for making this work available.
Umm, just updated to the latest version, still got the same error msg, I'm not sure if there's something that I missed here, I'm kinda new to all this github and stuff, so if you may just clearfiy a how to use demo.py more, please?
thanks for your time sir, much appreciated

just to tell what did i do so far:
1. cloned repo
2. downloaded jde.1088x608.uncertainty.py and got it under \weights\jde.1088x608.uncertainty.py
3. trying to use a sample video "ppl2.mp4" which is the same directory of the project
4. using the following cmd:
python demo.py --input-video C:\ppl2.mp4 --weights weights\jde.1088x608.uncertainty.pt --output-root C:\vseq
![11](https://user-images.githubusercontent.com/20155571/77328344-1282c900-6d25-11ea-82b5-e91b49800289.jpg)

and thanks again for your time and patience :)

**Comment by arielrakovitskyprinceton** [comment]
Hi, thanks for this great repo! I'm following the same steps as the above poster and having the same bug. Running on cpu.

**Comment by Zhongdao** [comment]
Hi @tamamjerbi,
According to your log, your GPU is out of memory.
@arielrakovitskyprinceton 
I don't think your case is the same as @tamamjerbi, because the "Could find no file" error emerges when ffmpeg fails in assembling the video from images, and the reason may vary. Please check your log carefully to find the true reason.

**Comment by tamamjerbi** [comment]
Hi @Zhongdao,
I don't think that my GPU running out of memory is what causing this, it is an issue but we're not there yet. I mean tried to follow the code, and found it's throwing exception in **demo.py**, line 61, so I followed that too and got an to **track.py**, line 92, and it stops there (before throwing the GPU memory thing) and got this **Epected type 'dtype', got 'Tensor' instead** and never reached beyond this line!!
thanks for your time :)


![debug_flags2](https://user-images.githubusercontent.com/20155571/77421448-8af49300-6dd4-11ea-8e0e-ca4cb7c4f13d.jpg)
![debug_flags3](https://user-images.githubusercontent.com/20155571/77421464-91830a80-6dd4-11ea-8384-dae01c5f37ba.jpg)

**Comment by Zhongdao** [comment]
@tamamjerbi ,
I don't know how PyCharm inferences data type, but the expected inputs of tracker.update() are indeed a pytorch tensor (im_blob) and a numpy ndarray (img0). Can you step in the tracker.update() method and see what is wrong inside?

**Comment by tamamjerbi** [comment]
Hi @Zhongdao,
Just did, stepped in and found that code stops at line 210 apparently, 
**pred = self.model(im_blob)** 
and doesn't go beyond this line. checked the type of **im_blob**, and it is indeed a Tensor but for some reason it doesn't execute this line, 210. I'm kinda confused not sure what the problem is.

Really appreciate your time.

![im_blob_](https://user-images.githubusercontent.com/20155571/77433827-9487f600-6de8-11ea-84b3-b7be5823bcd0.jpg)

**Comment by Zhongdao** [comment]
I am confused too because according to your log, the reason why the network forward fails is that your GPU runs out of memory. How large is your GPU memory? Could you try a smaller model, for instance, jde-576x320?

**Comment by tamamjerbi** [comment]
Hi @Zhongdao ,
thanks a lot for your time and patience, it did **work** finally!
I triend the smaller model but the problem was I didn't notice the cfg file, mismatch between the cfg file and the model.. but now it works completely fine... and once again thank you @Zhongdao 

just some final thought, say if I want to use live camera, is it possible?
and once more, thank you for your help!

**Comment by Zhongdao** [comment]
@tamamjerbi 
It's possible to use live camera, you just need to modify the dataloader a little. Note that I only measure the running time of the MOT system, and the outside code such as I/O and visualization is not optimized, so they may take some time.

**Comment by tamamjerbi** [comment]
Hi @Zhongdao,
That's good, I'll give it a try then.
And thank you a lot for sharing your work and time, much appreciated.

**Comment by shiguangliuguo** [comment]
Hi @tamamjerbi ,
Thanks a lot for your sharing question! I also had the same question as you.
But when I run the command:
python demo.py --input-video /home/aistudio/VID_20170318_104316.mp4 --weights /home/aistudio/data/data22239/jde_864x480.pt --output-format video --output-root /home/aistudio --cfg /home/aistudio/Towards-Realtime-MOT/cfg/yolov3_864x480.cfg

I still met the same qestion:
![image](https://user-images.githubusercontent.com/49485196/77819523-64a55f00-7116-11ea-8631-994a0ca2804d.png)

So could you please tell the detail that how you correct your code?

thanks for your time and author's great work.

**Comment by Zhongdao** [comment]
@shiguangliuguo 
The log says your GPU driver version is too old, you may need to update the driver to a newer version.

**Comment by shiguangliuguo** [comment]
> @shiguangliuguo
> The log says your GPU driver version is too old, you may need to update the driver to a newer version.

thanks your reply in a short time!
but turth be told, there is no GPU avalible in my computer.
So is there any chance to run this demo with CPU?
thanks for your time!

**Comment by Zhongdao** [comment]
It is possible to run on a CPU, but some modifications need to be done. You may need to remove all the `.cuda()` code.

**Comment by shiguangliuguo** [comment]
> It is possible to run on a CPU, but some modifications need to be done. You may need to remove all the `.cuda()` code.

That's is very helpful for me .
Thanks for your kindness and sharing spirit.
Have a good day!

**Comment by tamamjerbi** [comment]
Hi @shiguangliuguo,
couldn't give you any better solution than @Zhongdao 's solution! :)
wish you the best and thanks @Zhongdao for your effort.

**Comment by wulongjian** [comment]
Hi, I me the familiar problem, but my INFO is:
```bash
 [INFO]: Processing frame 0 (100000.00 fps)
2020-09-28 17:20:08 [INFO]: /home/wlj/anaconda3/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
ffmpeg version 4.3-2~16.04.york1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
```
Could you give me some advise?
