### ISSUE TITLE
the cython_bbox library is not matching with:python3.5 :cannot import name 'bbox_ious'

### ISSUE THREAD

**Issue by lyp-deeplearning** [Zhongdao/Towards-Realtime-MOT#13]
thanks for this great job! when i run this demo ,i meet a error:
`python3 demo.py --input-video /home/lyp/Videos/deploy1-155175756,155175757.mp4 --weights /home/lyp/project/mot-project/towards-realtime-mot/Towards-Realtime-MOT/jde.uncertainty.pt --output-format video --output-root /home/lyp/project/mot-project/towards-realtime-mot/
/usr/local/lib/python3.5/dist-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/home/lyp/project/mot-project/towards-realtime-mot/Towards-Realtime-MOT/tracker/multitracker.py", line 14, in <module>
    from tracker import matching
  File "/home/lyp/project/mot-project/towards-realtime-mot/Towards-Realtime-MOT/tracker/matching.py", line 7, in <module>
    from utils.cython_bbox import bbox_ious
ImportError: cannot import name 'bbox_ious'
`
i guess my python version is not matching with the cython_bbox.cpython-36m-x86_64-linux-gnu.so.
i find a 3.5 version file from https://github.com/microsoft/CNTK/tree/master/Examples/Image/Detection/utils/cython_modules, but this version file do not have the bbox_ious fuction.
Can you tell me about the file dir about cython_bbox.cpython-36m-x86_64-linux-gnu.so? i want a version with 3.5,thanks!

**Comment by feidasheng** [comment]
hello，i meet the same problem "cannot import box_ious", do you have solved this,thanks!

**Comment by simon-rob** [comment]
I got around the problem by:

pip install cython_bbox

change:
from utils.cython_bbox import bbox_ious
to:

from cython_bbox import bbox_overlaps as bbox_ious

**Comment by feidasheng** [comment]
thank you for your answer ,but i follow your  code  still   and cannot  import cython_bbox ,did you write correctly ?  thanks.

**Comment by simon-rob** [comment]
Do you have different versions of python on your machine?

If so you might have to use pip3 or pip3.5 (what ever it's called) 

what happens if you just type Python from the command line and then enter: 
from cython_bbox import bbox_overlaps as bbox_ious

do you get an error?

**Comment by feidasheng** [comment]
my version of python is 3.6, i use anaconda3  to create an environment and  my package is same as this github ,so strange

**Comment by feidasheng** [comment]
> I got around the problem by:
> 
> pip install cython_bbox
> 
> Change in matching.py:
> from:
> utils.cython_bbox import bbox_ious
> 
> to:
> from cython_bbox import bbox_overlaps as bbox_ious

Hello, the virtual python environment I am creating now is 3.7, so what is your environment? Is it because of this reason that the installed cython_boxs does not have box_ious?  thanks

**Comment by Zhongdao** [comment]
Hi guys,
Many thanks to @yanfengliu!
I have modified the code and now you can simply install cython_bbox via pip, as suggested in #40
