### ISSUE TITLE
Error(s) in loading state_dict for Darknet: size mismatch for classifier.weight

### ISSUE THREAD

**Issue by JoeyQWu** [Zhongdao/Towards-Realtime-MOT#130]
Hi guys, I got the problem "
Error(s) in loading state_dict for Darknet:
        size mismatch for classifier.weight: copying a param with shape torch.Size([7, 512]) from checkpoint, the shape in current model is torch.Size([14455, 512]).
        size mismatch for classifier.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([14455]).
" while I run the demo.py,
Where is the location of 14455?

**Comment by MrWWY** [comment]
I got the same problem,need help

**Comment by olaConge** [comment]
I got it,too. How do you solve this?

**Comment by fanshu4869** [comment]
#121
