### ISSUE TITLE
the embedding output 

### ISSUE THREAD

**Issue by zhangkui669** [Zhongdao/Towards-Realtime-MOT#132]
the model output = Bx(nAx6+512)xGxG, 512 is embedding feature length, nA is anchors num, this seems if one grid has two bbox output, they shared the same embedding features.
When two person is close enough, the center points if the two person fall into same grid, the embedding features seem to be ambiguous

**Comment by Zhongdao** [comment]
Yes, this is an intrinsic flaw of our method. Please refer to the recent follow-up work [FairMOT](https://github.com/ifzhang/FairMOT) for an available solution.
