### ISSUE TITLE
track.py issue

### ISSUE THREAD

**Issue by lzd-kennys** [Zhongdao/Towards-Realtime-MOT#134]
after i run `python track.py --cfg ./cfg/yolov3_1088x608.cfg --weights ./jde.uncertainty.pt`
there is an error: AttributeError: 'LoadImages' object has no attribute 'files'
if i miss some steps to test it on mot16 challenge?
hope to get your reply

**Comment by naziaperwaiz** [comment]
@lzd-kennys Will you please share how could you resolve this issue: LoadImages' object has no attribute 'files'.
Thanks.

**Comment by SanumNisar** [comment]
how did you resolve this?
