### ISSUE TITLE
Question: .seq in Caltech Pedestrian dataset

### ISSUE THREAD

**Issue by anhnktp** [Zhongdao/Towards-Realtime-MOT#139]
Great works !

I followed instruction at: https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md. 
However, with Caltech Pedestrian dataset, I downloaded all *.tar file from: http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/datasets/USA/ 
but I don't know how to convert *.seq file to sequence of .png file (or .jpg) 
With City Person dataset, I downloaded from Gdrive link but it seems Citypersons.z03 file is not final part zip 

Could you pls share link download Cityperson & Caltech_pedestrian dataset (have images & label_with_ids)

One more question, do your code support change custom detector instead of Yolov3 ?
Thank you so much !

**Comment by Zhongdao** [comment]
Hi please check this tool https://github.com/mitmul/caltech-pedestrian-dataset-converter
I will update the citypersons data and annotations, once done I will let you know.
Currently, we have not provided a different detector, but if this is your need, you can modify the detector by yourself.

**Comment by Zhongdao** [comment]
@anhnktp 
I just checked the data in Gdrive and it seems okay. I think the final part zip is Cityperons.zip. Could you try this:
```
cat Citypersons.z01 Citypersons.z02 Citypersons.z03 Citypersons.zip > c.zip
unzip c.zip
```

**Comment by anhnktp** [comment]
@Zhongdao 
Many thanks !! I tried again and extracted succesfully Cityperson dataset. But, folder 'images' has test set (6 sequences) but folder 'labels_with_ids' don't have, is that right ?
Tks. I converted Caltech dataset by that tool.

**Comment by Zhongdao** [comment]
@Zhongdao Yes, we do not use the test set, just leave them alone

**Comment by scangit** [comment]
> @anhnktp
> I just checked the data in Gdrive and it seems okay. I think the final part zip is Cityperons.zip. Could you try this:
> 
> ```
> cat Citypersons.z01 Citypersons.z02 Citypersons.z03 Citypersons.zip > c.zip
> unzip c.zip
> ```

Can you provide the checksum of all part of Citypersons. I try your command, but I can't unzip all the files and I get the following error:

Archive:  c.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [c.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
warning [c.zip]:  9437184000 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  9437184004
  (attempting to re-compensate)
=============================
ls Citypersons/images/train/

tubingen  ulm  weimar  zurich
