### ISSUE TITLE
Reduce Image size

### ISSUE THREAD

**Issue by kikirizki** [Zhongdao/Towards-Realtime-MOT#14]
Can I reduce image size without retrain the model?

**Comment by Zhongdao** [comment]
Yes, you had better set the height/width multiples of 32 (the down-sampling rate).
Since the model I provide is trained with the size 1088x608, if you reduce the image size, the performance may drop a bit. It should be better to retrain the model with the desired image size.

**Comment by kikirizki** [comment]
Thank you for your response
