### ISSUE TITLE
How to decompress Cityperson dataset?

### ISSUE THREAD

**Issue by scangit** [Zhongdao/Towards-Realtime-MOT#143]
I try  to decompress cityperson dataset:
`cat Citypersons.z01 Citypersons.z02 Citypersons.z03 Citypersons.zip > c.zip
unzip c.zip`

But I got the following error:
`Archive: c.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
(attempting to process anyway)
warning [c.zip]: zipfile claims to be last disk of a multi-part archive;
attempting to process anyway, assuming all parts have been concatenated
together in order. Expect "errors" and warnings...true multi-part support
doesn't exist yet (coming soon).
warning [c.zip]: 9437184000 extra bytes at beginning or within zipfile
(attempting to process anyway)
file #1: bad zipfile offset (local header sig): 9437184004
(attempting to re-compensate)`

I can only get partially unzipped files:
`ls Citypersons/images/train/
tubingen ulm weimar zurich`

Can you provide the checksum of all part of Citypersons?

**Comment by abutaufique** [comment]
I got the same problem..

**Comment by anhnktp** [comment]
@scangit  you can check https://github.com/Zhongdao/Towards-Realtime-MOT/issues/139

**Comment by abutaufique** [comment]
I am still getting the same problem after following #139. Only part of the files got unzipped.

**Comment by abutaufique** [comment]
Solved it!! Needed to repair the zip file after concatenation.

**Comment by scangit** [comment]
> Solved it!! Needed to repair the zip file after concatenation.

Thank you for your reply. I can decompress it correctly now. The command I use is:
`zip -FF Citypersons.zip --out c.zip`
then
uzip c.zip
