### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by ghm666** [Zhongdao/Towards-Realtime-MOT#15]
Thank you for your work, I encountered some errors while running the demo.py, can you help me?

```
`File "/usr/local/lib/python3.5/dist-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):

  File "/usr/local/lib/python3.5/dist-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)

  File "/usr/local/lib/python3.5/dist-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')

TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.`
```

**Comment by Zhongdao** [comment]
You can try uninstalled the old version of apex and reinstalled a new version.

git clone https://www.github.com/nvidia/apex
cd apex
python setup.py install

**Comment by ghm666** [comment]
> You can try uninstalled the old version of apex and reinstalled a new version.
> 
> git clone https://www.github.com/nvidia/apex
> cd apex
> python setup.py install

**Comment by ghm666** [comment]
Thank you very much, the code is working fine. 
There is still a question, how does this demo run on the GPU and the CPU runs very slowly?

**Comment by Zhongdao** [comment]
By default,  the model should run on a GPU. We have not achieved a real-time speed on CPU yet, it remains to be one of the future work for us.

**Comment by ghm666** [comment]
> By default, the model should run on a GPU. We have not achieved a real-time speed on CPU yet, it remains to be one of the future work for us.
Thank you very much！！！！
