### ISSUE TITLE
模型加载的问题

### ISSUE THREAD

**Issue by xuemin227** [Zhongdao/Towards-Realtime-MOT#16]
您好，我加载模型时出现以下问题：
2019-10-11 13:38:53 [INFO]: "filename 'storages' not found"
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[image2 @ 0x9bf940] Could find no file with path '/media/xuemin/CE1E49B3007246A9/results/frame/%05d.jpg' and index in the range 0-4
/media/xuemin/CE1E49B3007246A9/results/frame/%05d.jpg: No such file or directory

请教下您知道哪里出问题了吗？谢谢

**Comment by Zhongdao** [comment]
2019-10-11 13:38:53 [INFO]: "filename 'storages' not found"
Seems this path is wrong.

**Comment by xuemin227** [comment]
Thanks very much for your response!
I tried many times about the path,but the issue is still exists.Is it possible that there is a problem with the pt model form [Baidu NetDisk]?

**Comment by xuemin227** [comment]
My issue is solved. The model I download from baidu is wrong. Thank you very much!

**Comment by Zhongdao** [comment]
That's great, you are welcome.
