### ISSUE TITLE
I have two questions about creating a custom datasets.

### ISSUE THREAD

**Issue by yoonsoo-Shin** [Zhongdao/Towards-Realtime-MOT#163]
Thank you for your great research. I have two questions about creating a custom datasets.
1. Do you have tools for annotation and labeling in new videos(images) that can be applied to your code? My annotation tool cannot enter [identity].
2. Does [identity] mean the same person in a video? If 40 people appear in one video, is it correct that 0 to 39 are used for [identity]?

I'm eager to train with my own data.

**Comment by yoonsoo-Shin** [comment]
1. I used a similar tool to extract [x, y, w, h, label] and changed the format of the text file.
2. As a result of reading other Issues, I found out that I was right.

**Comment by mheriyanto** [comment]
>     1. I used a similar tool to extract [x, y, w, h, label] and changed the format of the text file.
> 
>     2. As a result of reading other Issues, I found out that I was right.

Thank you @yoonsoo-Shin . I have got insight from you.
