### ISSUE TITLE
'LoadImages' object has no attribute 'files'

### ISSUE THREAD

**Issue by tamamjerbi** [Zhongdao/Towards-Realtime-MOT#167]
Hello, @Zhongdao 
first of all, huge thanks for sharing your work here with us.
I was trying to run **track..py** as you mentioned in the readme file, and I downloaded the dataset you provided MOT16 but I have this weird error, I'm not sure what is the problem!
I try to run the following:
**python track.py --weights weights/jde.1088x608.uncertainty.pt --cfg cfg/yolov3_1088x608.cfg**

and I get this error msg:
2020-06-27 00:21:22 [INFO]: start seq: MOT17-02-SDP
Traceback (most recent call last):
  File "track.py", line 215, in <module>
    save_videos=opt.save_videos)
  File "track.py", line 135, in main
    dataloader = datasets.LoadImages(osp.join(data_root, seq, 'img1'), opt.img_size)
  File "E:\prj\utils\datasets.py", line 26, in __init__
    self.nF = len(self.files)  # number of image files
AttributeError: 'LoadImages' object has no attribute 'files'
![error_msg_2](https://user-images.githubusercontent.com/20155571/85902494-72957980-b804-11ea-873f-3d38570bc4d5.jpg)

thanks in advance :)

**Comment by SanumNisar** [comment]
how did you resolve this one?

**Comment by bbydgcs** [comment]
Excuse me, have you solved this problem? @tamamjerbi

**Comment by fanshu4869** [comment]
how did you resolve this？I meet a same problem
