### ISSUE TITLE
Concerns about the datasets used for training the models

### ISSUE THREAD

**Issue by mauro11-sant** [Zhongdao/Towards-Realtime-MOT#168]
First of all, congratulations on the work. I have been making modifications to the code and I have some concerns about the datasets used in the training. 

My doubt is if the provided models (**JDE-1088x608, JDE-864x480, JDE-576x320**) are trained with all the datasets of the DATASET_ZOO.md file except the MOT16 for validation. 

If so, that would be a problem since the **MOT17** and **MOT16** videos are the same ones, so the training and validation would overlap. 

I assume that the MOT17 is not part of the training, but I would like someone to confirm this if you would be so kind. 

 
Thank you for your response. Keep up the good work.

**Comment by Zhongdao** [comment]
Yes, MOT17 is used in training. For validation, we use MOT15 (which has no overlap videos with MOT17) in the paper. In readme.md I provide the tracking results on MOT16, that's not for validation, just for reference.
