### ISSUE TITLE
Why the Det and Emb test are quite different from those in papers?

### ISSUE THREAD

**Issue by Dgy2017** [Zhongdao/Towards-Realtime-MOT#169]
Has anyone tested `AP` and `TPR` for the pre-trained model  `jde.uncertainty.pt`? The results of my test are `AP=80.54` and `TPR@FAR =84`, which are  **quite different** from those of `AP=83.0` and `TPR=90.4` claimed in the paper. Except the `batch_size=8` All other hyperparameters were set as default.  The GPU used for this result is TITAN V.
Part of the output for Detection test:
![image](https://user-images.githubusercontent.com/26927195/86094751-86cac680-bae3-11ea-94c1-a09ca3365e6f.png)

Part of the output for Embeding  test:
![image](https://user-images.githubusercontent.com/26927195/86094890-b37ede00-bae3-11ea-9b20-1ba55467fb18.png)

**Comment by salt-fisher** [comment]
I have tested the mAP from the released pre-trained model.(Notice that the test dataset in configuration needs to be modified, the test dataset in paper only use Caltech). And i get a 0.8247 mAP, still a little lower than the 0.83 in paper. Beside, the released pre-trained model seems to train 60 epochs, while released code trains for 30 epochs

**Comment by Dgy2017** [comment]
> I have tested the mAP from the released pre-trained model.(Notice that the test dataset in configuration needs to be modified, the test dataset in paper only use Caltech). And i get a 0.8247 mAP, still a little lower than the 0.83 in paper. Beside, the released pre-trained model seems to train 60 epochs, while released code trains for 30 epochs

Thank you very much, I'll try it again later. Did you test the TPR score for `jde.uncertainty.pt`?

**Comment by Qizec** [comment]
> > I have tested the mAP from the released pre-trained model.(Notice that the test dataset in configuration needs to be modified, the test dataset in paper only use Caltech). And i get a 0.8247 mAP, still a little lower than the 0.83 in paper. Beside, the released pre-trained model seems to train 60 epochs, while released code trains for 30 epochs
> 
> Thank you very much, I'll try it again later. Did you test the TPR score for `jde.uncertainty.pt`?

Excuse me ,What is your final TPR score and AP?thanks
