### ISSUE TITLE
train on mot16

### ISSUE THREAD

**Issue by olaConge** [Zhongdao/Towards-Realtime-MOT#178]
I train on mot16 and get a weights, but when I test it, I meet this: 
RuntimeError: Error(s) in loading state_dict for Darknet:
	size mismatch for classifier.weight: copying a param with shape torch.Size([519, 512]) from checkpoint, the shape in current model is torch.Size([14455, 512]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([519]) from checkpoint, the shape in current model is torch.Size([14455]).

**Comment by fanshu4869** [comment]
#121
