### ISSUE TITLE
Can I use it to detect diseases in medical images? For instance, lung cancer in CT images?

### ISSUE THREAD

**Issue by alancarlosml** [Zhongdao/Towards-Realtime-MOT#180]
I am working with RetinaNet to detect lung cancer in CT images. I would like try your code to compare the results. Is it possible or it works with video input?

Regards.

**Comment by Ursanon** [comment]
You can easily input raw video with 
```
python demo.py --input-video <path to video> --weights <path to pretrained/baseline state_dict> --output-format video --output-root <output path>
```

**Comment by alancarlosml** [comment]
> You can easily input raw video with
> 
> ```
> python demo.py --input-video <path to video> --weights <path to pretrained/baseline state_dict> --output-format video --output-root <output path>
> ```

**Comment by alancarlosml** [comment]
@Ursanon Thank you for your reply. But I would like to know about use images instead video files.

**Comment by Ursanon** [comment]
@alancarlosml
I don't know (yet), but for now you can try merge files into movie with ffmpeg

**Comment by alancarlosml** [comment]
@Ursanon Yes It is an option. Today I am using a RetinaNet to detect the lesions, but i wish improve my results. 

Thank you!
