### ISSUE TITLE
Successful repetition demo.py

### ISSUE THREAD

**Issue by tensorflowt** [Zhongdao/Towards-Realtime-MOT#19]
The author's pedestrian tracking algorithm is excellent, better than yolov3 + deep sort, but the detection rate does not seem to be high？

**Comment by Zhongdao** [comment]
Glad to see that : )
The performance of detection may vary under different scenarios, you may tune the detection threshold to be lower for better recall, or higher for better precision. 
But I think the best way is to re-train the model with your own data, which comes from the same domain of your test data.

**Comment by tensorflowt** [comment]
Sorry, what I said before was wrong. What I want to say is that the detection speed is not very ideal, but the detection and tracking effect is very good!

**Comment by Zhongdao** [comment]
That's good... thank you for your comment! We will go on optimizing the speed of our system in the future.
