### ISSUE TITLE
 cannot import name 'SyncBN' from 'utils.syncbn' (unknown location)

### ISSUE THREAD

**Issue by Finniu** [Zhongdao/Towards-Realtime-MOT#20]
Hi, thanks for you awesome code, but when I try demo.py, I met this error, and I found there is nothing in the syncbn folder.

**Comment by leijuzi** [comment]
me either.i can find nothing in syncbn

**Comment by Finniu** [comment]
> me either.i can find nothing in syncbn

you can found the syncbn link in the requirements
