### ISSUE TITLE
Error in demo.py

### ISSUE THREAD

**Issue by ZhangwenguangHikvision** [Zhongdao/Towards-Realtime-MOT#21]
python demo.py --input-video test/MOT16-11.mp4 --weights weights/jde.uncertainty.pt --output-format text --output-root results/
Namespace(cfg='cfg/yolov3.cfg', conf_thres=0.5, img_size=(1088, 608), input_video='test/MOT16-11.mp4', iou_thres=0.5, min_box_area=200, nms_thres=0.4, output_format='text', output_root='results/', track_buffer=30, weights='weights/jde.uncertainty.pt')

2019-10-15 10:35:17 [INFO]: start tracking...
Lenth of the video: 900 frames
2019-10-15 10:35:21 [INFO]: Processing frame 0 (100000.00 fps)
2019-10-15 10:35:21 [INFO]: too many indices for array
no result was genrated, why there is too many indices for array?

**Comment by Zhongdao** [comment]
Can you figure out which line of code results in this?

**Comment by Zhongdao** [comment]
This issue is closed because no updates are replied, if you have any update please re-open this issue.
