### ISSUE TITLE
Got error when using yolov3-tiny.conv.15 and yolov3-tiny.cfg

### ISSUE THREAD

**Issue by mheriyanto** [Zhongdao/Towards-Realtime-MOT#224]
I got error when using yolov3-tiny.conv.15 (https://pjreddie.com/media/files/yolov3-tiny.conv.15) and yolov3-tiny.cfg (https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg) likes below:

```
Traceback (most recent call last):
  File "train.py", line 298, in <module>
    opt=opt,
  File "train.py", line 111, in train
    load_darknet_weights(model, osp.join(weights_from, 'yolov3-tiny.conv.15'))
  File "/content/gdrive/My Drive/bla-bla/models.py", line 334, in load_darknet_weights
    self.seen = header[3]  # number of images seen during training
IndexError: index 3 is out of bounds for axis 0 with size 0
```

Actually, I modified yolov3-tiny.cfg with adding `embedding_dim=512` in iine 10 and change anchors to `anchors = 14,10,  27,23,  58,37,  82,81,  169,135,  319,344` in line 135 and 177.

Are there any suggestions? Thanks.

**Comment by kikirizki** [comment]
would you mind post your cfg file

**Comment by mheriyanto** [comment]
> would you mind post your cfg file

Okay @kikirizki, this is [yolov3-tiny.cfg](https://drive.google.com/file/d/18xYeBjzOgr9kQ35qVolBaJeZr3k9HKhC/view?usp=sharing).

**Comment by mheriyanto** [comment]
Is there any update here?

**Comment by mheriyanto** [comment]
I closed this issue because this is duplicate issue with https://github.com/Zhongdao/Towards-Realtime-MOT/issues/32
