### ISSUE TITLE
why i got nan result?

### ISSUE THREAD

**Issue by datuizhuang** [Zhongdao/Towards-Realtime-MOT#228]
![image](https://user-images.githubusercontent.com/35105613/122850417-c2d3e880-d33f-11eb-87d4-935de764bd60.png)

i use this command:   python track.py --cfg ./cfg/yolov3_1088x608.cfg --weights weights/latest.pt --test-mot16 --save-images

and i check the detected image, is right.
![image](https://user-images.githubusercontent.com/35105613/122850700-4beb1f80-d340-11eb-8082-09e9053e5abc.png)

**Comment by Zhongdao** [comment]
You are running the test set of MOT-16, we do not have labels for the test split.
