### ISSUE TITLE
ImportError: cannot import name 'SyncBN'

### ISSUE THREAD

**Issue by leijuzi** [Zhongdao/Towards-Realtime-MOT#23]
firstly, thanks for your great jobs, when l try demo.py i met this error, could you give me some advice?  thank you very much

**Comment by Zhongdao** [comment]
If you do not need to train your own model you can just replace SyncBN with the normal pytorch BN.
See [here] (https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py#L12)

**Comment by leijuzi** [comment]
> If you do not need to train your own model you can just replace SyncBN with the normal pytorch BN.
> See [here] (https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py#L12)

thank you, but if i need to train detection, do i need this?

**Comment by Zhongdao** [comment]
Train with syncbn will be better,  here is the source code of syncbn used in this repo : https://github.com/ytoon/Synchronized-BatchNorm-PyTorch
