### ISSUE TITLE
How to do multiple classes training?

### ISSUE THREAD

**Issue by YueYuan95** [Zhongdao/Towards-Realtime-MOT#26]
I think the loss function is not consider the multiple classes loss in the `YOLOLayer`, How can I achieve the multiple calsses trianinig?

**Comment by Zhongdao** [comment]
Yes, multi-class training is not considered in this project. Actually, as far as I know, there is no such work as multi-class multi-object tracking with a single model yet. However, this is a good topic and we may work on this in the future.
