### ISSUE TITLE
CUHK-SYSU dataset error

### ISSUE THREAD

**Issue by meiyu422321** [Zhongdao/Towards-Realtime-MOT#27]
"CUHKSYSU/images/s6933.jpg" file path is not exist, however "CUHKSYSU/labels_with_ids/s6933.txt" is exist , casuse mismatch, can you slove the problem, please?

**Comment by Zhongdao** [comment]
Seems the uploaded file is incomplete, I will re-upload this dataset.

**Comment by Zhongdao** [comment]
@meiyu422321  The complete CUHK-SYSU dataset has been uploaded, please go to [DATASET_ZOO.md](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md) for download links.
