### ISSUE TITLE
demo with 864x408 image 

### ISSUE THREAD

**Issue by DANNALI35** [Zhongdao/Towards-Realtime-MOT#30]
Hi there, excellent work with real time MOT!
how can we run demo.py using 864x408 images as input? do we need another trained model? something like JDE-864x408-uncertainty?

**Comment by Zhongdao** [comment]
Yes model trained with 864x408 performs better on 864x408 resolution. But you can also use the 1088x608 model directly, by modifying input size. There will be a slight performance drop.

**Comment by DANNALI35** [comment]
thanks for such a prompt response! i tried to edit demo.py as follow, but i am getting this assert error `assert self.stride == img_size[1] / nGh` in model.py .
`parser.add_argument('--img-size', type=int, default=(864, 408), help='size of each image dimension')`
if i add np.ceil( img_size[1] / nGh) to model.py,  the assert error has gone, but another error shows.
`  File "/home/github/Towards-Realtime-MOT/models.py", line 242, in forward    
    x = torch.cat([layer_outputs[i] for i in layer_i], 1)    
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 51 and 52 in dimension 2`

**Comment by Zhongdao** [comment]
Sorry I have made a mistake in the tech report, the resolution should be multiples of 32 so it is 864x448 rather than 864x408.

**Comment by DANNALI35** [comment]
thanks, i managed to run the demo with 864x448 image
