### ISSUE TITLE
Undefined name: 'cpu_soft_nms'  in utils/utils.py

### ISSUE THREAD

**Issue by cclauss** [Zhongdao/Towards-Realtime-MOT#33]
[flake8](http://flake8.pycqa.org) testing of https://github.com/Zhongdao/Towards-Realtime-MOT on Python 3.8.0

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./utils/utils.py:421:12: F821 undefined name 'cpu_soft_nms'
    keep = cpu_soft_nms(np.ascontiguousarray(dets, dtype=np.float32),
           ^
1     F821 undefined name 'cpu_soft_nms'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by MIXALER** [comment]
I got the same issue

**Comment by cclauss** [comment]
https://www.google.com/search?q=cpu_soft_nms

**Comment by cclauss** [comment]
Bump on this one.

**Comment by Zhongdao** [comment]
Hi guys,
I think you can just leave this alone because soft_nms is not used for inference.  Or you can just delete all the code that is related to soft_nms.
