### ISSUE TITLE
help,help,help

### ISSUE THREAD

**Issue by sunanlin13174** [Zhongdao/Towards-Realtime-MOT#37]
i want to test the model by my video,so i run demo.py with my video, but no affect i see.
so could anybody gives me a tutorial about what's the order runing the code?

**Comment by Marjanmoodi** [comment]
python demo.py --input-video data/tennis.avi --weights pre_trained/darknet53.conv.74

You should put the downloaded weights (darknet53.conv.74) into "pre_trained" folder. Also In the command I put the video (tennis.avi) into data folder
