### ISSUE TITLE
dataloader can't be loop

### ISSUE THREAD

**Issue by DongDem** [Zhongdao/Towards-Realtime-MOT#4]
def eval_seq(opt, dataloader, data_type, result_filename, save_dir=None, show_image=True, frame_rate=30):
    if save_dir:
        mkdir_if_missing(save_dir)
    tracker = JDETracker(opt, frame_rate=frame_rate)
    timer = Timer()
    results = []
    frame_id = 0
    for path, img, img0 in dataloader:
        if frame_id % 20 == 0:
            logger.info('Processing frame {} ({:.2f} fps)'.format(frame_id, 1./max(1e-5, timer.average_time)))
dataloader can't be loop

**Comment by Zhongdao** [comment]
Hi, 
Could you please post more error information?

**Comment by DongDem** [comment]
When I run demo.py with input is video, the dataloader is iterations of the frame. But the code can't run into the loop to process. in track.py function eval_seq()
`
    for path, img, img0 in dataloader:
        print('tien')
        if frame_id % 20 == 0:
            logger.info('Processing frame {} ({:.2f} fps)'.format(frame_id, 1./max(1e-5, timer.average_time)))

        # run tracking
        timer.tic()
`
