### ISSUE TITLE
ffmpeg: error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory!

### ISSUE THREAD

**Issue by xiaocc612** [Zhongdao/Towards-Realtime-MOT#42]
2019-11-03 16:49:03 [INFO]: start tracking...
Lenth of the video: 900 frames
2019-11-03 16:49:05 [INFO]: CUDA error: out of memory
ffmpeg: error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

help!help ！！

**Comment by CrazySummerday** [comment]
> 2019-11-03 16:49:03 [INFO]: start tracking...
> Lenth of the video: 900 frames
> 2019-11-03 16:49:05 [INFO]: CUDA error: out of memory
> ffmpeg: error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
> 
> help!help ！！

How did you solved it?
