### ISSUE TITLE
Can't open result.mp4

### ISSUE THREAD

**Issue by xiaocc612** [Zhongdao/Towards-Realtime-MOT#43]
I get the result frames,but player can't open result.mp4

**Comment by Zhongdao** [comment]
You can try to change a player, I believe there must be an available one.

**Comment by xiaocc612** [comment]
Thanks,I write code to generate video with in python&opencv.Wondful work,thanks for sharing.

**Comment by huangpan2507** [comment]
I have tried many media players which are failed until when I use Tencent video， it works！！
