### ISSUE TITLE
Change class without retraining ?

### ISSUE THREAD

**Issue by kikirizki** [Zhongdao/Towards-Realtime-MOT#44]
Is there a way somehow to change the tracking from pedestrian detection to vehicle detection without retraining the network?

**Comment by Zhongdao** [comment]
Unfortunately the answer is no.

**Comment by kikirizki** [comment]
Thank you, as I guess. In the end I have no choice, just train the network with my old gtx1050. It cannot handle batch size larger than 1. I hope god will strengthen my heart

**Comment by Srenpan** [comment]
Hi @kikirizki , I'm interest in vehicle detection. Do you retraining the network? Can you provide the training weight or describe how to train on vehicle?

**Comment by kikirizki** [comment]
@Srenpan I don't train the network yet due to my limited resource. but I plan to use DETRAC-dataset here is I create oythkn script to translate from DETRAC-dataset to MOT yiu can use it and follow this repo instruction to train

**Comment by Srenpan** [comment]
Thank you for kindly reply!

**Comment by kikirizki** [comment]
@Srenpan Or yiu can use this https://github.com/kikirizki/DETRAC_dataset2Caltech_dataset then follow Zhongdao repo instruction
