### ISSUE TITLE
Will u support UA-DETRAC dataset?

### ISSUE THREAD

**Issue by kikirizki** [Zhongdao/Towards-Realtime-MOT#46]
Will you support for vehicle dataset too, such as UA-DETRAC?
btw I create UA-DETRAC to Caltech Pedestrian dataset here:
https://github.com/kikirizki/DETRAC_dataset2Caltech_dataset

**Comment by Zhongdao** [comment]
Thanks a lot! Multi-vechicle tracking is in our todo list, but we cannot guarantee when this will be finished. It depends on if our paper is accepted.

**Comment by kikirizki** [comment]
Looking forward your next paper, .. thanks you for your great work
