### ISSUE TITLE
the speed cannot achieve the speed the paper declare, 18 fps

### ISSUE THREAD

**Issue by xinguanxi** [Zhongdao/Towards-Realtime-MOT#47]
hi, this is a wonderful work on MOT, but i run the demo.py, and only 3-4 fps, the video i run is TownCentreXVID.avi, this video is 1080p. i check the code, there is a resize, so i do not know what is the difference

**Comment by xinguanxi** [comment]
and hardware is  
Intel® Core™ i7-7700 CPU @ 3.60GHz × 8 
gpu nvidia 1060 
memory  16G

**Comment by ThanhPham1987** [comment]
Please contact to me so that i can support you. My skype :quangthanh1987

**Comment by xinguanxi** [comment]
sorry，i do not have skype,  could u tell me where is the difference ?

**Comment by Zhongdao** [comment]
I think your hardware is the reason, the reported speed is tested on an Nvidia Titan xp

**Comment by Zhongdao** [comment]
You can also check #48, with an Nvidia 1080 the FPS is around 15 FPS.

**Comment by xinguanxi** [comment]
ok,  i will try this on 2080ti, thank u for this kind reply

**Comment by ciwei123** [comment]
@xinguanxi Do you run this code on 2080ti？Could you tell me the speed? Thank you very much!
