### ISSUE TITLE
issue in demo ( invalid load key, '\x00')

### ISSUE THREAD

**Issue by aeadod** [Zhongdao/Towards-Realtime-MOT#51]
When I use 
python demo.py --input-video a.mp4 --weights darknet53.conv.74 --output-format text
It shows
2019-11-16 16:36:15 [INFO]: start tracking...
Lenth of the video: 106 frames
2019-11-16 16:36:15 [INFO]: invalid load key, '\x00'.
Is anybody know how to solve it ? Thanks.

**Comment by Srenpan** [comment]
You can try weight JDE-1088x608-uncertainty from author provide.

**Comment by Masao-Taketani** [comment]
@Srenpan Thanks! It fixed my problem!

**Comment by mauro11-sant** [comment]
Well, if you want to use darknet you need to change lines 160 and 161 of multitracker.py from:

```
#load_darknet_weights(self.model, opt.weights)
self.model.load_state_dict(torch.load(opt.weights, map_location='cpu')['model'], strict=False)
```
to

```

 load_darknet_weights(self.model, opt.weights)
# self.model.load_state_dict(torch.load(opt.weights, map_location='cpu')['model'], strict=False)
```

and it would work like a charm!

**Comment by ks322181** [comment]
i have modified. invalid load key error is fixed. But i am getting a new error. 
python: symbol lookup error. 
Undefined symbol: PySlice_Unpack

can any help me to resolve this?

**Comment by Scheaven** [comment]
> You can try weight JDE-1088x608-uncertainty from author provide.

I use the author's jde.uncertainty.pt（ JDE-1088x608-uncertainty ）,error:

2020-03-17 16:42:46 [INFO]: Error(s) in loading state_dict for Darknet:
	size mismatch for classifier.weight: copying a param with shape torch.Size([14455, 512]) from checkpoint, the shape in current model is torch.Size([30, 512]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([14455]) from checkpoint, the shape in current model is torch.Size([30]).
