### ISSUE TITLE
Requirements Towards-Realtime-MOT vs maskrcnn-benchmark 

### ISSUE THREAD

**Issue by kilarinikhil** [Zhongdao/Towards-Realtime-MOT#52]
Towards-Realtime-MOT says "Pytorch >= 1.0.1" while "maskrcnn-benchmark" says "pytorch 1.0 from nightly release". Can someone help me in which version of pytorch to install!

**Comment by yanfengliu** [comment]
I just built and ran their code last night with `pytorch=1.2.0` successfully. Make sure it has `cudatoolkit=10.0`, not 10.1, otherwise you will run into problems with `apex`

**Comment by kilarinikhil** [comment]
My nvcc was not being detected because the directory was not included in my PATH. Correcting it solved the problem. Thank you so much for spending your valuable time in going through my issue. I hereby close this issue.
