### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by yanfengliu** [Zhongdao/Towards-Realtime-MOT#53]
I think it should be specified that in the annotation files `[class]` should be set to 0, instead of saying 
> The field `[class]` is not used in this project since we only care about a single class, i.e., pedestrian here.

because in `test.py` the predicted class is hardcoded to be 
```
pred_cls=np.zeros_like(detections[:, 5])
```
So if someone accidentally sets all classes = 1 in the annotation files they will have very bad scores and not know why.

**Comment by Zhongdao** [comment]
Thank you! I will modify the documentation.
