### ISSUE TITLE
some questions about loss

### ISSUE THREAD

**Issue by pby5** [Zhongdao/Towards-Realtime-MOT#54]
1.when compute multiple weighted loss,  the init values set are -4.15, -4.85, -2.3, how to get these values?
2.in your code, use softmax loss to compute embeddings, but in papers use triplet loss, which loss compute embeddings?

**Comment by Zhongdao** [comment]
1. These values correspond to loss weights 64,64,0.1, which is a good initialization.
2. Actually, in the paper, we discuss why we DO NOT use triplet loss, and why we use CE loss:
![image](https://user-images.githubusercontent.com/14846754/70385767-3bc45700-19cb-11ea-8e27-96821c3ae28a.png)
