### ISSUE TITLE
Can it be used to train my own image data to identify and track other objects?

### ISSUE THREAD

**Issue by spy14414** [Zhongdao/Towards-Realtime-MOT#55]
Hi,
   I'm learning multi-object tracking. I found that basically the tracked objects of MOT are pedestrians.
Can I use your project to track other objects？Such as kiwi?  I want to use the eye-in-hand system to pick kiwi.So I need to track kiwi.
  Can you help me?
  Thanks in advance.
  ps.大佬，我的中式英语是不是有点丢人...

**Comment by Zhongdao** [comment]
Yes, and you need to prepare your own training data with the same format as described in https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md.

By the way, I guess your task may be better solved by Detection + Single Object Tracking. You can have a try, just a suggestion.
