### ISSUE TITLE
Format of training data

### ISSUE THREAD

**Issue by Marjanmoodi** [Zhongdao/Towards-Realtime-MOT#58]
When I download the Caltech dataset from this link: http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/datasets/USA/ 
The format of images are .seq and there is no .png, .jpg and .txt int it. Should I convert the dataset to the right format myself?

**Comment by Vankeee** [comment]
Just search it on google..

**Comment by Zhongdao** [comment]
@Marjanmoodi Check this repo: https://github.com/mitmul/caltech-pedestrian-dataset-converter

**Comment by Marjanmoodi** [comment]
@Zhongdao Thanks
