### ISSUE TITLE
about the ignore area in the dataset

### ISSUE THREAD

**Issue by ZongweiZhou1** [Zhongdao/Towards-Realtime-MOT#59]
Hey @Zhongdao 

It is an excellent job. And I want to use the dataset you provided in this repo to train my model, but i am confusing whether the ignore area of annotation in origin dataset are considered here?

**Comment by Zhongdao** [comment]
Not yet. For convenience, I just discard images that contain ignore areas, since the joint training set is sufficient in data quantity.
