### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lijuanzhou** [Zhongdao/Towards-Realtime-MOT#6]
import motmetrics as mm
ModuleNotFoundError: No module named 'motmetrics'

hello!while i am running demo.py,the above error occured, but i can not find the motmetrics module.why?

**Comment by Zhongdao** [comment]
Hi,
py-motmetrics is an evaluation library for MOT, you can simply install it by pip:
`pip install motmetrics`

**Comment by lijuanzhou** [comment]
thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhongdaoWang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月8日(星期二) 晚上9:41
收件人:&nbsp;"Zhongdao/Towards-Realtime-MOT"<Towards-Realtime-MOT@noreply.github.com&gt;;
抄送:&nbsp;"雨痕"<1203606512@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhongdao/Towards-Realtime-MOT] import error (#6)




Hi,
 py-motmetrics is an evaluation library for MOT, you can simply install it by pip:
 pip install motmetrics

**Comment by huangpan2507** [comment]
who can help me？
>>(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$ python demo.py --input-video  test/MOT16-12.mp4  --weights weights/jde_864x480_uncertainty.pt  --output-format video --output-root results/
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    import motmetrics as mm
ModuleNotFoundError: No module named 'motmetrics'
(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$ pip list | grep motmetricss
(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$ conda list | grep  motmetrics
motmetrics                1.2.0                    pypi_0    pypi
(Towards-Realtime-MOT) [huangpan@logos-server Towards-Realtime-MOT]$

I have  used conda install motmetrics，But why it still went wrong？ Any idea is appreciated！
