### ISSUE TITLE
demo.py issue

### ISSUE THREAD

**Issue by pacearthur** [Zhongdao/Towards-Realtime-MOT#63]
Hi,

Can someone help me about this issue ?

![Capture](https://user-images.githubusercontent.com/33637884/70871147-5df64000-1f9c-11ea-8242-86146168bdf2.PNG)

**First :**
"Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

**And also:**
"[image2 @ 0000021d85b49580] Could find no file with path 'results\frame/%05d.jpg' and index in the range 0-4 results\frame/%05d.jpg: No such file or directory"

Indeed I don't have any NVIDIA GPU on my computer but I thought that it will be possible to run the demo.py script

**Comment by pacearthur** [comment]
And this is what I have when I execute command 'nvcc --version' :

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105

**Comment by leonel11** [comment]
> And this is what I have when I execute command 'nvcc --version' :
> 
> **nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2019 NVIDIA Corporation Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019 Cuda compilation tools, release 10.1, V10.1.105**

The same problem. How can I solve it? Please, let me know, if you coped with it
(I have an opportunity to launch this program on NVIDIA GPU card
Cuda compilation tools, release 10.1, V10.1.243)
