### ISSUE TITLE
Spelling Mistakes

### ISSUE THREAD

**Issue by Harleks** [Zhongdao/Towards-Realtime-MOT#65]
>  CUDA_VISIBLE_DEIVCES=0,1,2,3,4,5,6,7 python train.py

“DEIVCES” should be “DEVICES”
This confused me for half an hour to debug...

**Comment by DN-ghm** [comment]
> > CUDA_VISIBLE_DEIVCES=0,1,2,3,4,5,6,7 python train.py
> 
> “DEIVCES” should be “DEVICES”
> This confused me for half an hour to debug...

me too

**Comment by Zhongdao** [comment]
Thank you for pointing out the mistake, I have corrected it in the latest README.md
Sorry for the inconvenience!
