### ISSUE TITLE
STrack questions

### ISSUE THREAD

**Issue by soldierofhell** [Zhongdao/Towards-Realtime-MOT#66]
Hi @Zhongdao,

I have two questions about STrack class:
1. Why in predict(), if state is not Tracked, you zero one of the state variables (velocity of h)?
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/1cb8cee836cbc7ffb905e969d9c2cf44c686324b/tracker/multitracker.py#L48
2. In update_features() you normalize smooth_feat, but I can't find this kind of normalization for feat input?
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/1cb8cee836cbc7ffb905e969d9c2cf44c686324b/tracker/multitracker.py#L41

Regards,

**Comment by Zhongdao** [comment]
Hi @soldierofhell,
For the first question, we find that setting the velocity to zero decreases the ID switches. Keeping predicting the states of lost tracklets indeed brings more ID recall, but in more cases, the tracklets tend to drift, which introduces many wrong assignments. Therefore the overall IDS increases. We are looking for a better association algorithm to address these problems.
For the second question, this line of code is not a normalization, but a feature updating strategy. We maintain a single feature vector for a tracklet by moving-averaging the features in each frame, with a momentum \alpha.

**Comment by soldierofhell** [comment]
Thanks @Zhongdao, as for the second question maybe I should have quoted better line. Here exactly you're doing normalization:
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/1cb8cee836cbc7ffb905e969d9c2cf44c686324b/tracker/multitracker.py#L43
So in previous quoted line you're doing update where one component is normalized and the other not (or I haven't found where it is :)

**Comment by soldierofhell** [comment]
And to the first question, that's reasonable what you've written, but you only zero vh. Shouldn't you zero the whole velocity vector (vx, vy, va, vh)?

**Comment by Zhongdao** [comment]
I'm sorry for the second question: It is a mistake. I have updated the [code](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/7216bcaadff1f3465e0b2e1cc48e1e13d95372a4/models.py#L198), the model now outputs normalized embedding. 

As for zeroing the velocity, we have not investigated whether it is good to zero the whole velocity vector (vx, vy, va, vh).  This part of code is adapted from [longcw/MOTDT](https://github.com/longcw/MOTDT).

**Comment by soldierofhell** [comment]
Thank you, now everything is perfectly clear :)
