### ISSUE TITLE
Training on other dataset

### ISSUE THREAD

**Issue by Srenpan** [Zhongdao/Towards-Realtime-MOT#68]
@Zhongdao Hi, I try to train on UA-DETRAC dataset for tracking vehicle, but I get no detection of the car. 
As I follow by the data format, [class] [identity] [x_center] [y_center] [width] [height], I set the car class to zero and follow the data format.
But after training 5 epoch, I use the `test` code to check the map and always get the value of 0.
And I use the demo code, but the model can't get the detection of the car.
Should I try to change the yolov3.cfg anchor size? or other code or the setting should I revised but I ignored?

**Comment by imranzaman5202** [comment]
Hi there, 

Im wondering if you ran the model on UA_DETRACK dataset and for tracking vehicles successfully?

If yes please can you share the code with me at imranzaman.5202@gmail.com. Thanks

**Comment by Zhongdao** [comment]
Hi @Srenpan,
I suggest you change the anchor ratio to fit the vehicle sizes. But even if the anchor ratio is not proper, the model should still produce decent results rather than 0 mAP. Have you solved this problem?

**Comment by Srenpan** [comment]
Hi @Zhongdao ,
I have solved this problem by change the anchor ratio to 1:1 and the mAP is not zero. 
Before I change the anchor, the training batch size is 2, and the detection conf is very low equal to 0.1 or lower, so the mAP is zero. 
After I freeze the backbone (Darkent53 ) layer, I can set my batch size to 6 and mAP is increase to 70%.
I think the problem caused the mAP to zero may be the small batch size and the wrong anchor ratio caused the bad training results.

**Comment by Zhongdao** [comment]
@Srenpan Thanks a lot!

**Comment by minitho** [comment]
Can i ask if someone still have the dataset. I cant find it anywhere.

**Comment by mheriyanto** [comment]
> Can i ask if someone still have the dataset. I cant find it anywhere.

Hi @minitho , what dataset don't you can find?

**Comment by minitho** [comment]
The DETRAC dataset, i find the images but i cant download the labels

**Comment by minitho** [comment]
> > Can i ask if someone still have the dataset. I cant find it anywhere.
> 
> Hi @minitho , what dataset don't you can find?

The DETRAC dataset, i find the images but i cant download the labels

**Comment by JackWoo0831** [comment]
> 
@Srenpan Hello, may I ask in a correct situation what is the value of **conf** should be?
I trained on MOT17 in 5 epochs and the **conf** decreased from 2.06 to 0.1, is it normal?

**Comment by irfanfadhullah** [comment]
Hello @Srenpan , can you share your full repo or code to irfanfadhullah@sju.ac.kr ? I want to reproduce your result. But there are lot of problem . Thank you
