### ISSUE TITLE
PRW dataset txt not found

### ISSUE THREAD

**Issue by chandanrao007** [Zhongdao/Towards-Realtime-MOT#69]
OSError: Towards-Realtime-MOT-master\PRW/labels_with_ids/c1s1_000151.txt not found.

The txt file is present in that folder but also it is showing it is not found.I'm using windows

**Comment by chandanrao007** [comment]
changed the path

**Comment by NaifahNurya** [comment]
Hellow, @chandanrao007  can you clarify more on this, because i get the same problem when i run the code on my dataset  as you can see in this issue  https://github.com/Zhongdao/Towards-Realtime-MOT/issues/160

Kindly, Ineed your help
