### ISSUE TITLE
Could you give some descriptions about training Datasets?

### ISSUE THREAD

**Issue by dbofseuofhust** [Zhongdao/Towards-Realtime-MOT#7]
Hey, Thanks for you excellent work, I want to train this repo on my own dataset, could you give instructions for training dataset composed? Expect to be answered!

**Comment by Zhongdao** [comment]
Hi, 
Sorry that I have some other stuff to deal with these days so I cannot update the code and instruction in time, but I will return to this project as soon as possible (maybe one week), please key an eye on this repo.
Thanks for your interests!

**Comment by alasijia** [comment]
Hey, I have the same question.when I run train.py, it shows the error,Is a directory: './data/mot17.train,i don't know the train data. Could you  give some descriptions about training Datasets.

**Comment by yds5817** [comment]
@alasijia Hello! I have the same problem. Have you solved it？

**Comment by Zhongdao** [comment]
Hi guys, training datasets are available now, please check DATASET_ZOO.md.

**Comment by dbofseuofhust** [comment]
Thanks for you r kind dataset description!
