### ISSUE TITLE
Segmentation fault when run demo.py

### ISSUE THREAD

**Issue by Tylerjoe** [Zhongdao/Towards-Realtime-MOT#71]
Thanks for your good works, but when I run the demo.py, I have met a error: Segmentation fault  when the code run at utils/utils.py(line457).
could you please give me some advices

**Comment by Zhongdao** [comment]
It seems that NMS has some problems.
I have updated the code recently, the codebase does not rely on maskrcnn-benchmark anymore because I switch to the official pytorch implementation of GPU NMS. Please update your pytorch to version > 1.2.0 and try again.

**Comment by Tylerjoe** [comment]
Thanks very much
