### ISSUE TITLE
Cuda out of memory error

### ISSUE THREAD

**Issue by chandanrao007** [Zhongdao/Towards-Realtime-MOT#72]
Whenever I run train.py file I get this error.

RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 4.00 GiB total capacity; 2.78 GiB already allocated; 3.35 MiB free; 147.37 MiB cached)

Can I train it on the CPU.

**Comment by Zhongdao** [comment]
Your GPU memory is not sufficient for training, for 864x480 resolution the memory cost is at least 8GB.
I do not think training on CPU is a good idea.

**Comment by josuerocha** [comment]
Hi @Zhongdao ,

Is there a way to reduce memory usage for training? I would like to bring it down to at most 7GB.

Thanks

**Comment by Zhongdao** [comment]
Hi @josuerocha 
You can use lower input resolution and smaller batch size.

**Comment by josuerocha** [comment]
Thanks for your reply @Zhongdao .

Is it enough to set **img_size**  and **batch_size** to lower values?
