### ISSUE TITLE
[INFO]: invalid load key, '\x00'

### ISSUE THREAD

**Issue by DongDem** [Zhongdao/Towards-Realtime-MOT#8]
Have error line: [INFO]: invalid load key, '\x00' when run demo.py
in JDETracker function to load pretrained weights

tracker = JDETracker(opt, frame_rate=frame_rate)
  File "tracker/multitracker.py", line 158, in __init__
    self.model.load_state_dict(torch.load(opt.weights, map_location='cpu')['model'], strict=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by Zhongdao** [comment]
Hi, is this model the one you load?
https://drive.google.com/open?id=1nlnuYfGNuHWZztQHXwVZSL_FvfE551pA

**Comment by DongDem** [comment]
Thanks you for your uploading. This pretrained weights is OK
