### ISSUE TITLE
Real-time use

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#81]
How to make this code work for real-time object tracking? I want to take continuous sequence from web-cam and want to track people in it.

**Comment by Zhongdao** [comment]
Hi @PartheshSoni ,
You can write a web-cam dataloader following the [LoadVideo](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/dee692baf0bcf9c7d6ce5a435c31e78939c8f8d0/utils/datasets.py#L79) class.
