### ISSUE TITLE
Some questions on implementations

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#83]
What is the difference between TrackState.tracked and strack.is_activated intuitively? What does the first one used for?

**Comment by Zhongdao** [comment]
The only difference between `TrackState.tracked` and `strack.is_acitvated` is, when an strack is initialized for the first time, we set `strack.stage =  TrackState.tracked` but `strack.is_activated` is still `False`.  `strack.is_activated` will be set  to `True`  when this strack is associated by another observation (via IOU distance) in the consecutive frames. 

That's to say, an strack is initialized only when it is associated by at least two observations. This will reduce some false alarms.

**Comment by PartheshSoni** [comment]
Okay thanks!
