### ISSUE TITLE
Error in using self-trained weights in demo.py 

### ISSUE THREAD

**Issue by PartheshSoni** [Zhongdao/Towards-Realtime-MOT#85]
I trained the model with MOT15 dataset. The training processes looked successful (The loss decreased constantly). I didn't ran the test and test_embeddings code though (I commented it out for now). Now while using the self-trained weights, I am getting the following error: 

![Screenshot from 2020-02-06 17-49-40](https://user-images.githubusercontent.com/24564303/73936693-65d1c100-4909-11ea-9926-c8b875599975.png)

I am not able to understand what went wrong. Please help.

**Comment by PartheshSoni** [comment]
Also, what should I do to avoid such error.

**Comment by PartheshSoni** [comment]
I changed the nID to 30 and it worked for some frames, but not it suddenly stopped, indicating division by zero error in some frame. By the way, what is nID? And what can I do regarding the issue?

**Comment by Zhongdao** [comment]
Hi @PartheshSoni,
nID is the number of training identities. Actually it should be not required in testing, I will fix the code to solve this issue in the next version. You can just set nID to 30 and everything will be okay.

As for the division by zero error, I guess it's another issue, can you please post the error trace? I need to know where the error occurs.

**Comment by PartheshSoni** [comment]
I trained the model from scratch just for knowing more about the training process. I commented out the Calculate mAP section(and test_emb section). I used 3D MOT15 dataset for training (Just two training video sequences). The training looked successful as the loss reduced almost consistently(from ~96 to ~6). No. of epochs was set to 30. When I tested using the train data itself(Just to make sure that the model overfitted, hence training process would be sucessful), it went fine. But when I used one other video sequence(Link: https://www.youtube.com/watch?v=6NBwbKMyzEE), I got this error: 
![1](https://user-images.githubusercontent.com/24564303/74006490-d88e7b00-49a1-11ea-855c-976734ec8a90.png)
![2](https://user-images.githubusercontent.com/24564303/74006495-d9bfa800-49a1-11ea-8bde-9d6318ecc182.png)

Partially tracked video is stored in the result though. Please let me know if you need some more details.

**Comment by imchwan** [comment]
Hi @PartheshSoni ,
I also have the same problem. (The 1st one you mentioned. size mismatch...)
How did you solved the problem?

Below is the messages I've got.
----------------------------------------------------------------------------------------------------------------------------------
Namespace(cfg='./cfg/yolov3_1088x608.cfg', conf_thres=0.5, iou_thres=0.5, min_box_area=200, nms_thres=0.4, save_images=True, save_videos=False, test_mot16=True, track_buffer=30, weights='/mnt/choong/Towards-Realtime-MOT/weights/jde.1088x608.uncertainty.pt')

2020-03-19 10:25:17 [INFO]: start seq: MOT16-01
Traceback (most recent call last):
  File "track.py", line 220, in <module>
    save_videos=opt.save_videos)
  File "track.py", line 141, in main
    save_dir=output_dir, show_image=show_image, frame_rate=frame_rate)
  File "track.py", line 79, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/mnt/choong/Towards-Realtime-MOT/tracker/multitracker.py", line 164, in __init__
    self.model.load_state_dict(torch.load(opt.weights, map_location='cpu')['model'], strict=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Darknet:
        size mismatch for classifier.weight: copying a param with shape torch.Size([14455, 512]) from checkpoint, the shape in current model is torch.Size([30, 512]).
        size mismatch for classifier.bias: copying a param with shape torch.Size([14455]) from checkpoint, the shape in current model is torch.Size([30]).

**Comment by PartheshSoni** [comment]
In the file tracker/multitracker.py, change the nID while initializing Darknet to 30.

Something like this:

`def` __init__(self, opt, frame_rate=30):
--
160 | self.opt = opt
161 | self.model = Darknet(opt.cfg, opt.img_size, nID=30)`
