### ISSUE TITLE
Different detected objects share same embedded feature.

### ISSUE THREAD

**Issue by WongKinYiu** [Zhongdao/Towards-Realtime-MOT#88]
Different objects detected by different anchors in a same grid have same embedded feature.
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py#L204
It will causes the near objects have totally same embedded feature when tracking.
I think it may be the main reason why ID switch (IDs) is so high of JDE.
![image](https://user-images.githubusercontent.com/12152972/74119409-3fa66c80-4bfa-11ea-96d1-4c3cee49fee9.png)

Do you have good ideas to deal with this problem?
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py#L175-L193
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/models.py#L204

And could you provide the result of following setting?
| Method | Det | Emb | #box | #id |
| :-: | :-: | :-: | :-: | :-: |
| DeepSORT_2 | JDE | WRN | 270k | 1.2k |

**Comment by Zhongdao** [comment]
Hi @WongKinYiu ,
You are right, targets with large overlaps share quite similar (or identical) embedding. This is a part of the reasons why the IDS is so high.
I believe in separate detection + reID systems this is also a problem. There are several ways to solve this issue, for instance, introducing more fine-grained correspondence [1].  I believe It's a promising direction to address this problem.
Regarding the experiments,  by far I can provide a similar setting:
DeepSORT + JDE-Detecotr + PCB ReID model , resolution 1088x608
The MOTA is around 64, and the IDS is around 1600.
