### ISSUE TITLE
ZeroDivisionError: float division by zero When running demo.py

### ISSUE THREAD

**Issue by 6zc** [Zhongdao/Towards-Realtime-MOT#90]
`python demo.py --input-video cctv.mp4 --weights darknet53.conv.74 --output-format video --output-root output1.mp4 --cfg cfg/yolov3_864*480.cfg
Namespace(cfg='cfg/yolov3_864x480.cfg', conf_thres=0.5, input_video='cctv.mp4', iou_thres=0.5, min_box_area=200, nms_thres=0.4, output_format='video', output_root='output1.mp4', track_buffer=30, weights='darknet53.conv.74')

2020-02-11 11:22:00 [INFO]: start tracking...
Traceback (most recent call last):
  File "demo.py", line 66, in <module>
    track(opt)
  File "demo.py", line 35, in track
    dataloader = datasets.LoadVideo(opt.input_video, opt.img_size)
  File "/home/lzc/Projects/Towards-Realtime-MOT/utils/datasets.py", line 91, in __init__
    self.w, self.h = self.get_size(self.vw, self.vh, self.width, self.height)
  File "/home/lzc/Projects/Towards-Realtime-MOT/utils/datasets.py", line 95, in get_size
    wa, ha = float(dw) / vw, float(dh) / vh
ZeroDivisionError: float division by zero
`
I am wondering that is the resolution of the input video must be exactly 864.480 or it doesn't matter?
The video I use is 864.486.

**Comment by Zhongdao** [comment]
Hi @6zc ,
The height and width must be multiples of 32. Just use the default setting and the videos will be automatically resized.

**Comment by 6zc** [comment]
Thank you for your reply! Problem solved:)
