### ISSUE TITLE
calculate anchors

### ISSUE THREAD

**Issue by DN-ghm** [Zhongdao/Towards-Realtime-MOT#94]
How is your anchor calculated?

anchors = 8,24, 11,34, 16,48, 23,68,   32,96, 45,135, 64,192, 90,271,   128,384, 180,540, 256,640, 512,640

**Comment by asnorkin** [comment]
See the original paper on arxiv
https://arxiv.org/pdf/1909.12605.pdf

"Learning to detect"  paragraph

**Comment by Zhongdao** [comment]
Hi @DN-ghm ,
I think @asnorkin has already addressed your concern, so this issue is closed.
