### ISSUE TITLE
unable to extract MOT17.zip (from google drive) file

### ISSUE THREAD

**Issue by sachingoyal0104** [Zhongdao/Towards-Realtime-MOT#98]
I guess it is not comppressed properly

**Comment by danielzgsilva** [comment]
Hi I also get this issue. Were you able to resolve?

**Comment by chuxiaoselena** [comment]
I got this as well, how did you fix it?

**Comment by danielzgsilva** [comment]
> I got this as well, how did you fix it?

I just used the images from the MOT16 dataset, since MOT16 and MOT17 share the same images, and just downloaded the MOT17 annotations from the MOT challenge website
