### ISSUE TITLE
Problem running in Google Colab

### ISSUE THREAD

**Issue by FloWuenne** [Zhongdao/Towards-Realtime-MOT#99]
Hi,

I am trying to run the demo with a test video from YouTube inside of Google Colab but I am getting an error similar to #38 although I am using the current weights and configs:

```
[image2 @ 0x55c3e6952000] Could find no file with path './frame/%05d.jpg' and index in the range 0-4
./frame/%05d.jpg: No such file or directory
```
The Google Colab with the code can be found here:

https://colab.research.google.com/drive/1Ydpt6mT7dD0w_vEM12osfQRB077Y5axm

Thanks for helping with this!

**Comment by jugi92** [comment]
Dont know if it is still relevant, but I reused your colab and it is working:
https://colab.research.google.com/drive/1PANKX9WETfYfa2pol7k4OwH22PESnWjh
one thing that failed was the download of the .pt files as those are to big for direct download

**Comment by jugi92** [comment]
But unfortunately it only runs with 14 fps max, far from realtime

**Comment by FloWuenne** [comment]
Thanks for the fix! This issue can be closed!
